repository:
  name: slipstream
  description: |
    a websocket client
  private: true
  has_issues: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  topics: websocket

teams:
  - name: devs
    permission: admin

collaborators:
  - username: cuatrobuild
    permission: push

labels:
  - name: Good Example
    color: 1d76db
  - name: p:Critical
    color: e11d21
  - name: p:High
    color: eb6420
  - name: p:Low
    color: 009800
  - name: p:Medium
    color: fbca04
  - name: s:Abandoned
    color: '000000'
  - name: s:Accepted
    color: 009800
  - name: s:Accept?
    color: ededed
  - name: s:Available
    color: bfe5bf
  - name: s:Blocked
    color: e11d21
  - name: s:Completed
    color: 006b75
  - name: s:In Progress
    color: bfd4f2
  - name: s:On Hold
    color: d4c5f9
  - name: s:Pending
    color: fef2c0
  - name: s:Review Needed
    color: fbca04
  - name: s:Revision Needed
    color: e99695
  - name: t:Bug
    color: e11d21
  - name: t:Enhancement
    color: 84b6eb
  - name: t:Feature
    color: c2e0c6
  - name: t:Maintenance
    color: fbca04
  - name: t:Question
    color: cc317c
  - name: t:Redesign
    color: d93f0b
  - name: t:Refactor
    color: 5319e7
  - name: t:Test
    color: d4c5f9
  - name: t:Tech Debt
    color: fef2c0
  - name: t:Beer Money
    color: cc8e47
  - name: dfm
    color: dbb127
  - name: baemax
    color: fef2c0
  - name: team-money
    color: 26b5a9
  - name: team-food
    color: e2d14f
  - name: team-yer-welcome
    color: fc9c8f
  - name: corporal-llama
    color: f99ab1
  - name: platform
    color: 7010b5
  - name: pinned
    color: 0e8a16
  - name: stale
    color: ffffff

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ["Bless"]
      enforce_admins: false
      restrictions: null

# Generated by Elixir.Gaas.Generators.Simple.GithubSettings
