locals_without_parens = [
  route_event: 2,
  route_command: 1,
  callback: 2
]

[
  inputs: ["mix.exs", "{config,lib,test}/**/*.{ex,exs}"],
  import_deps: [],
  locals_without_parens: locals_without_parens,
  export: [],
  line_length: 80
]

# Generated by Elixir.Gaas.Generators.Simple.Formatter
