defmodule Slipstream.MixProject do
  use Mix.Project

  @version_file Path.join(__DIR__, ".version")
  @external_resource @version_file
  @version (case Regex.run(~r/^v([\d\.\w-]+)/, File.read!(@version_file),
                   capture: :all_but_first
                 ) do
              [version] -> version
              nil -> "0.0.0"
            end)

  def project do
    [
      app: :slipstream,
      version: @version,
      elixir: "~> 1.6",
      elixirc_paths: elixirc_paths(Mix.env()),
      compilers: extra_compilers(Mix.env()) ++ Mix.compilers(),
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      preferred_cli_env: [
        credo: :test,
        coveralls: :test,
        "coveralls.html": :test,
        bless: :test,
        test: :test
      ],
      test_coverage: [tool: ExCoveralls],
      package: package(),
      description: description(),
      source_url: "https://github.com/NFIBrokerage/slipstream",
      name: "Slipstream",
      docs: docs()
    ]
  end

  defp elixirc_paths(env) when env in [:dev, :test], do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  defp extra_compilers(env) when env in [:dev, :test], do: [:phoenix]
  defp extra_compilers(_), do: []

  def application do
    if Mix.env() in [:dev, :test] do
      [
        mod: {Slipstream.Application, []},
        extra_applications: [:logger, :runtime_tools]
      ]
    else
      []
    end
  end

  defp deps do
    [
      {:gun, "~> 1.3"},
      {:telemetry, "~> 0.4"},
      {:jason, "~> 1.0", optional: true},
      {:nimble_options, "~> 0.1"},
      # docs
      {:ex_doc, ">= 0.0.0", only: :dev, runtime: false},
      # test
      {:phoenix, "~> 1.5", only: [:dev, :test]},
      {:cowlib, "~> 2.9", override: true, only: [:dev, :test]},
      {:phoenix_pubsub, "~> 2.0", only: [:dev, :test]},
      {:plug_cowboy, "~> 2.0", only: [:dev, :test]},
      {:bless, "~> 1.0"},
      {:convene, "~> 0.2", organization: "cuatro", only: [:dev, :test]},
      {:excoveralls, "~> 0.7", only: :test}
    ]
  end

  defp package do
    [
      name: "slipstream",
      files: ~w(lib .formatter.exs mix.exs README.md .version),
      licenses: [],
      organization: "cuatro",
      links: %{"GitHub" => "https://github.com/NFIBrokerage/slipstream"}
    ]
  end

  defp description do
    "a websocket client"
  end

  defp docs do
    [
      # do you reference other projects in your documentation? if so, add
      # them to the :deps key here. for an example, see
      # https://github.com/NFIBrokerage/projection/blob/5f406872d00156e2b94cfa9fae8e92a1aa4c177b/mix.exs#L88-L90
      deps: [],
      extras: [
        "CHANGELOG.md"
      ],
      groups_for_extras: [
        Guides: Path.wildcard("guides/*.md")
      ]
    ]
  end
end

# Generated by Elixir.Gaas.Generators.Simple.LibraryMix
